version: '3'

services:
  osticket:
    image: campbellsoftwaresolutions/osticket
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secret

      # CHANGE ME
      - INSTALL_SECRET=secret
    links:
      - osticket_mysql:mysql
    ports:
      - "8080:80"
    depends_on:
      - osticket_mysql
    restart: always

  osticket_mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secret
    volumes:
      - /opt/volumes/osticket_mysql:/var/lib/mysql
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - osticket
    restart: always 
